apiVersion: apps/v1
kind: Deployment
metadata:
  name: primuslearning
  labels:
    app: primuslearning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: primuslearning
  template:
    metadata:
      name: tsimagnova
      labels:
        app: primuslearning
    spec:
      containers:
        - name: devopsambo
          image: 089250994305.dkr.ecr.us-east-2.amazonaws.com/devopsambo:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080