name: Node js app deploy to eks
on: 
 push:
   branches: [ " main" ]
 pull_request:
   branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.24.0' # default is latest stable
      id: install

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Login to Amazon ECR Public
      id: login-ecr-public
      uses: aws-actions/amazon-ecr-login@v2
      with:
          registry-type: public

    - name: Build, tag, and push docker image to Amazon ECR Public
      env:
          REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          REPOSITORY: my-ecr
          IMAGE_TAG: 1.1
      run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

    - name: Update kube config
      run: aws eks update-kubeconfig --name my-ecr

    - name: Deploy to EKS
      run: |
           kubectl apply -f deployment.yaml
           kubectl apply -f service.yaml
     

       
